/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HnRouteImport } from './routes/hn'
import { Route as IndexRouteImport } from './routes/index'

const HnRoute = HnRouteImport.update({
  id: '/hn',
  path: '/hn',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hn': typeof HnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hn': typeof HnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hn': typeof HnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/hn'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hn'
  id: '__root__' | '/' | '/hn'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HnRoute: typeof HnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/hn': {
      id: '/hn'
      path: '/hn'
      fullPath: '/hn'
      preLoaderRoute: typeof HnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HnRoute: HnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
